name: "welcome to the code-languages"

on:
    push:
        branches:
            - main
            - test-1
            - production-1

jobs:
    hello-world:
    runs-on: ubuntu-latest

    steps:
        - name: "print the statement"
          run : echo "welcome to the devops world"
