name : "welcome to devbharath"

on:
  push:
    branches:
        - main
        - test-1
        - production-1

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name : "checkout nodeCode"
              run : echo "welcome to the node code and data transfer"