name: "welcome to devbharath yaml code"

on:
    push:
        branches:
            - main
            - test-1

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: "welcome to checkout@v4"
              run: echo "you are done"
            - name: "print the date"
              run: date
