name: "welcome to multiple pipline yaml code"

on:
    push:
        branches:
            - main
            - test-1
            - production-1
jobs:
    on_push-request:
        runs-on: ubuntu-latest
        steps:
            - name: "welcome to node-checkout@v4"
              run: echo "you are done with multiple pipline"

    on_pull-request:
        runs-on: ubuntu-latest
        steps:
            - name: "welcome to node-checkout@v4 for pull request"
              run: echo "you are done with multiple pipline for pull request"
            - name: "print the date for pull request"
              run: date