name: "welcome to multiple pipeline yaml code"

on:
    push:
        branches:
            - main
            - test-1
            - production-1
    pull_request:
        branches:
            - main
            - test-1
            - production-

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: "welcome to checkout@v4"
              run: echo "you are done with multiple pipeline"

            - name: "print the date function"
              run: date
