name : "multiple pipline workFlow"

on:
  push:
    branches:
      - main
      - test-1
      - production-2 
  pull_request:
    branches:
      - main
      - test-1
      - production-2

jobs:
  push:
    if: ${{github.event_name =='push'}}
    runs-on: ubuntu-latest
    steps:
      - name: "welcome to checkout@v4"
        run: echo "you are done"
      - name: "print the date"
        run: date
  pull_request:
    if: ${{github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
      - name: "welcome to checkout@v4"
        run: echo "you are in pull_request"
      - name: "print the date and time"
        run: date +"%Y-%m-%d %H:%M:%S"