name: "welcome to multiple pipline run"

on:
  push:
    branches:
      - main
      - master
      - production-1
      - test-1
  pull_request:
    branches:
      - main
      - master
      - test-1
      - production-1

jobs:
  push_request:
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'push'}}
    steps:
      - name: "welcome to print date"
        run: echo date

      - name: "welcome to the world"
        run: echo "welcome to devbharath github actions"

  pull_request:
      runs-on : ubuntu-latest
      if : ${{github.event_name == 'pull_request'}}
      steps:
         - name: "print the date function"
           run: echo date 
