name: "welcome to multiple pipeline"

on:
  push:
    branches:
      - main
      - test-1
      - production-1
  pull_request:
    branches:
      - main
      - test-1
      - production-1

jobs:
  push_request:
    if: ${{github.event_name == 'push'}}
    runs-on: ubuntu-latest
    steps:
      - name: "checkout readme"
        run: cat README.md

      - name: "print branch name"
        run: echo "The branch name is dev"

  pull_request:
    if: ${{github.event_name =='pull_request'}}
    runs-on: ubuntu-latest
    steps:
      - name: "checkout readme"
        run: cat README.md

      - name: "print branch name"
        run: echo "The branch name is ${{ github.head_ref }}"
