name: "multiple level pipline script language"

on:
  push:
    branches:
      - main
      - test-1
      - production-1
  pull_request:
    branches:
      - main
      - test-1
      - production-1
jobs:
  push_request:
    if: ${{github.event_name == 'push'}}
    runs-on: ubuntu-latest
    steps:
      - name: checkout Verfication code in node-Js
        run: echo "print hello devbharath"

  pull_request:
    if: ${{github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
      - name: checkout Verfication code in python
        run: echo "print('hello devbharath' pull code)"
