name: "welcome to multiple pipline"

on:
  push:
    branches:
      - main
      - test-1
      - production-1
  pull_request:
    branches:
      - main
      - test-1
      - production-1

jobs:
  push_request:
    if: ${{github.event_name == 'push'}}
    runs-on: ubuntu-latest
    steps:
      - name: checkout nodeJs
        run: |
          echo "welcome to nodejs"

      - name: checkout python
        run: |
          echo "welcome to python"

  pull_request:
    if: ${{github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
      - name: checkout nodeJs
        run: |
          echo "welcome to nodejs"

      - name: checkout python
        run: |
          echo "welcome to python"
