name: "multiple level pipline script language"

on:
    push:
        branches:
            - master
            - production-1
            - test-1
    pull_request:
            branches:
                - master
                - production-1
                - test-1
jobs:
    on_push_request:
        if: ${{github.event_name == 'push'}}
        runs-on : ubuntu-latest
        steps:
            - name: "welcome to checkout@v4"
              run: echo "you are done with multiple level pipline"
            - name: "print the date"
              run: date
    
    on_pull_request:
        if: ${{github.event_name == 'pull_request'}}
        runs-on : ubuntu-latest
        steps:
            - name: "welcome to checkout@v4 for pull request"
              run: echo "you are done with multiple level pipline for pull request"
            - name: "print the date for pull request"
              run: date
